import styles from '../styles/Mobile.module.css'
import Head from 'next/head'
export default function Mobile() {
  return (
    <>
      <Head>
        <title>Burnout Bots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mobile}>
        <div className={styles.message}>
          A fatal exception 0FB has occurred, Y0U'R3:L05T. The application you attempted to access is only available on desktop
        </div>
      </div>
    </>

  )
} 